/*
 * Copyright (c) 2010 Borisov Alexandr
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Borisov Alexandr <b0ric.alex@gmail.com>
 */

#include "../tty.h"
#include "../keybd.h"

/* array to map key codes to equvalent ASCII char */
keycode_t key_map[] = {
/* code */   /* char */       /* SHIFT */      /* Alt */     /* SHIFT-Alt */  /* ESC seq */
/*  00  */      0,              0,              Alt(0),         Alt(0),         0,
/*  01  */      SP(ESCKEY),     SP(ESCKEY),     SP(ESCKEY),     SP(ESCKEY),     0,
/*  02  */      '1',            '!',            Alt('1'),       Alt('!'),       0,
/*  03  */      '2',            '@',            Alt('2'),       Alt('@'),       0,
/*  04  */      '3',            '#',            Alt('3'),       Alt('#'),       0,
/*  05  */      '4',            '$',            Alt('4'),       Alt('$'),       0,
/*  06  */      '5',            '%',            Alt('5'),       Alt('%'),       0,
/*  07  */      '6',            '^',            Alt('6'),       Alt('^'),       0,
/*  08  */      '7',            '&',            Alt('7'),       Alt('&'),       0,
/*  09  */      '8',            '*',            Alt('8'),       Alt('*'),       0,
/*  0A  */      '9',            '(',            Alt('9'),       Alt('('),       0,
/*  0B  */      '0',            ')',            Alt('0'),       Alt(')'),       0,
/*  0C  */      '-',            '_',            Alt('-'),       Alt('_'),       0,
/*  0D  */      '=',            '+',            Alt('='),       Alt('+'),       0,
/*  0E  */      '\b',           '\b',           Alt('\b'),      Alt('\b'),      0,
/*  0F  */      '\t',           '\t',           Alt('\t'),      Alt('\t'),      0,
/*  10  */      'q',            'Q',            Alt('q'),       Alt('Q'),       0,
/*  11  */      'w',            'W',            Alt('w'),       Alt('W'),       0,
/*  12  */      'e',            'E',            Alt('e'),       Alt('E'),       0,
/*  13  */      'r',            'R',            Alt('r'),       Alt('R'),       0,
/*  14  */      't',            'T',            Alt('t'),       Alt('T'),       0,
/*  15  */      'y',            'Y',            Alt('y'),       Alt('Y'),       0,
/*  16  */      'u',            'U',            Alt('u'),       Alt('U'),       0,
/*  17  */      'i',            'I',            Alt('i'),       Alt('I'),       0,
/*  18  */      'o',            'O',            Alt('o'),       Alt('O'),       0,
/*  19  */      'p',            'P',            Alt('p'),       Alt('P'),       0,
/*  1A  */      '[',            '{',            Alt('['),       Alt('{'),       0,
/*  1B  */      ']',            '}',            Alt(']'),       Alt('}'),       0,
/*  1C  */      '\n',           '\n',           Alt('\n'),      Alt('\n'),      '\n',
/*  1D  */      SP(LCTRL),      SP(LCTRL),      SP(LCTRL),      SP(LCTRL),      SP(RCTRL),
/*  1E  */      'a',            'A',            Alt('a'),       Alt('A'),       0,
/*  1F  */      's',            'S',            Alt('s'),       Alt('S'),       0,
/*  20  */      'd',            'D',            Alt('d'),       Alt('D'),       0,
/*  21  */      'f',            'F',            Alt('f'),       Alt('F'),       0,
/*  22  */      'g',            'G',            Alt('g'),       Alt('G'),       0,
/*  23  */      'h',            'H',            Alt('h'),       Alt('H'),       0,
/*  24  */      'j',            'J',            Alt('j'),       Alt('J'),       0,
/*  25  */      'k',            'K',            Alt('k'),       Alt('K'),       0,
/*  26  */      'l',            'L',            Alt('l'),       Alt('L'),       0,
/*  27  */      ';',            ':',            Alt(':'),       Alt(':'),       0,
/*  28  */      '\'',           '\"',           Alt('\"'),      Alt('\"'),      0,
/*  29  */      '`',            '~',            Alt('`'),       Alt('~'),       0,
/*  2A  */      SP(LSHIFT),     SP(LSHIFT),     SP(LSHIFT),     SP(LSHIFT),     0,
/*  2B  */      '\\',           '|',            Alt('\\'),      Alt('|'),       0,
/*  2C  */      'z',            'Z',            Alt('z'),       Alt('Z'),       0,
/*  2D  */      'x',            'X',            Alt('x'),       Alt('X'),       0,
/*  2E  */      'c',            'C',            Alt('c'),       Alt('C'),       0,
/*  2F  */      'v',            'V',            Alt('v'),       Alt('V'),       0,
/*  30  */      'b',            'B',            Alt('b'),       Alt('B'),       0,
/*  31  */      'n',            'N',            Alt('n'),       Alt('N'),       0,
/*  32  */      'm',            'M',            Alt('m'),       Alt('M'),       0,
/*  33  */      ',',            '<',            Alt(','),       Alt('<'),       0,
/*  34  */      '.',            '>',            Alt('.'),       Alt('>'),       0,
/*  35  */      '/',            '?',            Alt('/'),       Alt('?'),       '/',
/*  36  */      SP(RSHIFT),     SP(RSHIFT),     SP(RSHIFT),     SP(RSHIFT),     0,
/*  37  */      '*',            '*',            Alt('*'),       Alt('*'),       0,
/*  38  */      SP(LALT),       SP(LALT),       SP(LALT),       SP(LALT),       SP(RALT),
/*  39  */      ' ',            ' ',            Alt(' '),       Alt(' '),       0,
/*  3A  */      SP(CAPS),       SP(CAPS),       SP(CAPS),       SP(CAPS),       0,
/*  3B  */      SP(F1),         S(SP(F1)),      A(SP(F1)),      AS(SP(F1)),     0,
/*  3C  */      SP(F2),         S(SP(F2)),      A(SP(F2)),      AS(SP(F2)),     0,
/*  3D  */      SP(F3),         S(SP(F3)),      A(SP(F3)),      AS(SP(F3)),     0,
/*  3E  */      SP(F4),         S(SP(F4)),      A(SP(F4)),      AS(SP(F4)),     0,
/*  3F  */      SP(F5),         S(SP(F5)),      A(SP(F5)),      AS(SP(F5)),     0,
/*  40  */      SP(F6),         S(SP(F6)),      A(SP(F6)),      AS(SP(F6)),     0,
/*  41  */      SP(F7),         S(SP(F7)),      A(SP(F7)),      AS(SP(F7)),     0,
/*  42  */      SP(F8),         S(SP(F8)),      A(SP(F8)),      AS(SP(F8)),     0,
/*  43  */      SP(F9),         S(SP(F9)),      A(SP(F9)),      AS(SP(F9)),     0,
/*  44  */      SP(F10),        S(SP(F10)),     A(SP(F10)),     AS(SP(F10)),    0,
/*  45  */      SP(NUM),        SP(NUM),        SP(NUM),        SP(NUM),        0,
/*  46  */      SP(SCROLL),     SP(SCROLL),     SP(SCROLL),     SP(SCROLL),     0,
/*  47  */      SP(KP7),        SP(KP7),        SP(KP7),        SP(KP7),        SP(HOME),
/*  48  */      SP(KP8),        SP(KP8),        SP(KP8),        SP(KP8),        SP(UP),
/*  49  */      SP(KP9),        SP(KP9),        SP(KP9),        SP(KP9),        SP(PGUP),
/*  4A  */      '-',            '-',            Alt('-'),       Alt('-'),       0,
/*  4B  */      SP(KP4),        SP(KP4),        SP(KP4),        SP(KP4),        SP(LEFT),
/*  4C  */      SP(KP5),        SP(KP5),        SP(KP5),        SP(KP5),        0,
/*  4D  */      SP(KP6),        SP(KP6),        SP(KP6),        SP(KP6),        SP(RIGHT),
/*  4E  */      '+',            '+',            Alt('+'),       Alt('+'),       0,
/*  4F  */      SP(KP1),        SP(KP1),        SP(KP1),        SP(KP1),        SP(END),
/*  50  */      SP(KP2),        SP(KP2),        SP(KP2),        SP(KP2),        SP(DOWN),
/*  51  */      SP(KP3),        SP(KP3),        SP(KP3),        SP(KP3),        SP(PGDOWN),
/*  52  */      SP(KP0),        SP(KP0),        SP(KP0),        SP(KP0),        SP(INS),
/*  53  */      SP(KPDOT),      SP(KPDOT),      SP(KPDOT),      SP(KPDOT),      SP(DEL),
/*  54  */      0,              0,              0,              0,              0,
/*  55  */      0,              0,              0,              0,              0,
/*  56  */      0,              0,              0,              0,              0,
/*  57  */      0,              0,              0,              0,              0,
/*  58  */      0,              0,              0,              0,              0,
/*  59  */      0,              0,              0,              0,              0,
/*  5A  */      0,              0,              0,              0,              0,
/*  5B  */      0,              0,              0,              0,              SP(LGUI),
/*  5C  */      0,              0,              0,              0,              SP(RGUI),
/*  5D  */      0,              0,              0,              0,              SP(APPS),
/*  5E  */      0,              0,              0,              0,              0,
/*  5F  */      0,              0,              0,              0,              0,
/*  60  */      0,              0,              0,              0,              0,
/*  61  */      0,              0,              0,              0,              0,
/*  62  */      0,              0,              0,              0,              0,
/*  63  */      0,              0,              0,              0,              0,
/*  64  */      0,              0,              0,              0,              0,
/*  65  */      0,              0,              0,              0,              0,
/*  66  */      0,              0,              0,              0,              0,
/*  67  */      0,              0,              0,              0,              0,
/*  68  */      0,              0,              0,              0,              0,
/*  69  */      0,              0,              0,              0,              0,
/*  6A  */      0,              0,              0,              0,              0,
/*  6B  */      0,              0,              0,              0,              0,
/*  6C  */      0,              0,              0,              0,              0,
/*  6D  */      0,              0,              0,              0,              0,
/*  6E  */      0,              0,              0,              0,              0,
/*  6F  */      0,              0,              0,              0,              0,
/*  70  */      0,              0,              0,              0,              0,
/*  71  */      0,              0,              0,              0,              0,
/*  72  */      0,              0,              0,              0,              0,
/*  73  */      0,              0,              0,              0,              0,
/*  74  */      0,              0,              0,              0,              0,
/*  75  */      0,              0,              0,              0,              0,
/*  76  */      0,              0,              0,              0,              0,
/*  77  */      0,              0,              0,              0,              0,
/*  78  */      0,              0,              0,              0,              0,
/*  79  */      0,              0,              0,              0,              0,
/*  7A  */      0,              0,              0,              0,              0,
/*  7B  */      0,              0,              0,              0,              0,
/*  7C  */      0,              0,              0,              0,              0,
/*  7D  */      0,              0,              0,              0,              0,
/*  7E  */      0,              0,              0,              0,              0,
/*  7F  */      0,              0,              0,              0,              0
};

