/*
 * Copyright (c) 2010 Borisov Alexandr
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Borisov Alexandr <b0ric.alex@gmail.com>
 */

#include "../keybd.h"

/* array to map key codes to equvalent ASCII char */
keycode_t key_map[] = {
/* code */   /* char */       /* SHIFT */      /* ALT */      /* CTRL */
/*  00  */      0,              0,              A(0),           0,
/*  01  */      SP(ESCKEY),     SP(ESCKEY),     A(ESCKEY),      SP(ESCKEY),
/*  02  */      '1',            '!',            A('1'),         C('1'),
/*  03  */      '2',            '@',            A('2'),         C('2'),
/*  04  */      '3',            '#',            A('3'),         C('3'),
/*  05  */      '4',            '$',            A('4'),         C('4'),
/*  06  */      '5',            '%',            A('5'),         C('5'),
/*  07  */      '6',            '^',            A('6'),         C('6'),
/*  08  */      '7',            '&',            A('7'),         C('7'),
/*  09  */      '8',            '*',            A('8'),         C('8'),
/*  0A  */      '9',            '(',            A('9'),         C('9'),
/*  0B  */      '0',            ')',            A('0'),         C('0'),
/*  0C  */      '-',            '_',            A('-'),         C('-'),
/*  0D  */      '=',            '+',            A('='),         C('='),
/*  0E  */      '\b',           '\b',           A('\b'),        C('\b'),
/*  0F  */      '\t',           '\t',           A('\t'),        C('\t'),
/*  10  */      'q',            'Q',            A('q'),         C('q'),
/*  11  */      'w',            'W',            A('w'),         C('w'),
/*  12  */      'e',            'E',            A('e'),         C('e'),
/*  13  */      'r',            'R',            A('r'),         C('r'),
/*  14  */      't',            'T',            A('t'),         C('t'),
/*  15  */      'y',            'Y',            A('y'),         C('y'),
/*  16  */      'u',            'U',            A('u'),         C('u'),
/*  17  */      'i',            'I',            A('i'),         C('i'),
/*  18  */      'o',            'O',            A('o'),         C('o'),
/*  19  */      'p',            'P',            A('p'),         C('p'),
/*  1A  */      '[',            '{',            A('['),         C('['),
/*  1B  */      ']',            '}',            A(']'),         C(']'),
/*  1C  */      '\n',           '\n',           A('\n'),        C('\n'),
/*  1D  */      SP(LCTRL),      SP(LCTRL),      SP(LCTRL),      SP(LCTRL),
/*  1E  */      'a',            'A',            A('a'),         C('a'),
/*  1F  */      's',            'S',            A('s'),         C('s'),
/*  20  */      'd',            'D',            A('d'),         C('d'),
/*  21  */      'f',            'F',            A('f'),         C('f'),
/*  22  */      'g',            'G',            A('g'),         C('g'),
/*  23  */      'h',            'H',            A('h'),         C('h'),
/*  24  */      'j',            'J',            A('j'),         C('j'),
/*  25  */      'k',            'K',            A('k'),         C('k'),
/*  26  */      'l',            'L',            A('l'),         C('l'),
/*  27  */      '\'',           '\"',           A('\''),        C('\''),
/*  28  */      ';',            ':',            A(';'),         C(';'),
/*  29  */      '`',            '~',            A('`'),         C('`'),
/*  2A  */      SP(LSHIFT),     SP(LSHIFT),     SP(LSHIFT),     SP(LSHIFT),
/*  2B  */      '\\',           '|',            A('\\'),        C('\\'),
/*  2C  */      'z',            'Z',            A('z'),         C('z'),
/*  2D  */      'x',            'X',            A('x'),         C('x'),
/*  2E  */      'c',            'C',            A('c'),         C('c'),
/*  2F  */      'v',            'V',            A('v'),         C('v'),
/*  30  */      'b',            'B',            A('b'),         C('b'),
/*  31  */      'n',            'N',            A('n'),         C('n'),
/*  32  */      'm',            'M',            A('m'),         C('m'),
/*  33  */      ',',            '<',            A(','),         C(','),
/*  34  */      '.',            '>',            A('.'),         C('.'),
/*  35  */      '/',            '?',            A('/'),         C('/'),
/*  36  */      SP(RSHIFT),     SP(RSHIFT),     SP(RSHIFT),     SP(RSHIFT),
/*  37  */      '*',            '*',            A('*'),         C('*'),
/*  38  */      SP(LALT),       SP(LALT),       SP(LALT),       SP(LALT),
/*  39  */      ' ',            ' ',            A(' '),         C(' '),
/*  3A  */      SP(CAPS),       SP(CAPS),       SP(CAPS),       SP(CAPS),
/*  3B  */      SP(F1),         S(SP(F1)),      SP(F1),         C(SP(F1)),
/*  3C  */      SP(F2),         S(SP(F2)),      SP(F2),         C(SP(F2)),
/*  3D  */      SP(F3),         S(SP(F3)),      SP(F3),         C(SP(F3)),
/*  3E  */      SP(F4),         S(SP(F4)),      SP(F4),         C(SP(F4)),
/*  3F  */      SP(F5),         S(SP(F5)),      SP(F5),         C(SP(F5)),
/*  40  */      SP(F6),         S(SP(F6)),      SP(F6),         C(SP(F6)),
/*  41  */      SP(F7),         S(SP(F7)),      SP(F7),         C(SP(F7)),
/*  42  */      SP(F8),         S(SP(F8)),      SP(F8),         C(SP(F8)),
/*  43  */      SP(F9),         S(SP(F9)),      SP(F9),         C(SP(F9)),
/*  44  */      SP(F10),        S(SP(F10)),     SP(F10),        C(SP(F10)),
/*  45  */      SP(NUM),        SP(NUM),        SP(NUM),        SP(NUM),
/*  46  */      SP(SCROLL),     SP(SCROLL),     SP(SCROLL),     SP(SCROLL),
/*  47  */      SP(KP7),        S(SP(KP7)),     SP(KP7),        C(SP(KP7)),
/*  48  */      SP(KP8),        S(SP(KP8)),     SP(KP8),        C(SP(KP8)),
/*  49  */      SP(KP9),        S(SP(KP9)),     SP(KP9),        C(SP(KP9)),
/*  4A  */      '-',            '-',            A('-'),         C('-'),
/*  4B  */      SP(KP4),        S(SP(KP4)),     SP(KP4),        C(SP(KP4)),
/*  4C  */      SP(KP5),        S(SP(KP5)),     SP(KP5),        C(SP(KP5)),
/*  4D  */      SP(KP6),        S(SP(KP6)),     SP(KP6),        C(SP(KP6)),
/*  4E  */      '+',            '+',            A('+'),         C('+'),
/*  4F  */      SP(KP1),        S(SP(KP1)),     SP(KP1),        C(SP(KP1)),
/*  50  */      SP(KP2),        S(SP(KP2)),     SP(KP2),        C(SP(KP2)),
/*  51  */      SP(KP3),        S(SP(KP3)),     SP(KP3),        C(SP(KP3)),
/*  52  */      SP(KP0),        S(SP(KP0)),     SP(KP0),        C(SP(KP0)),
/*  53  */      SP(KPDOT),      S(SP(KPDOT)),   SP(KPDOT),      C(SP(KPDOT)),
/*  54  */      0,              0,              0,              0,
/*  55  */      0,              0,              0,              0,
/*  56  */      0,              0,              0,              0,
/*  57  */      0,              0,              0,              0,
/*  58  */      0,              0,              0,              0,
/*  59  */      0,              0,              0,              0,
/*  5A  */      0,              0,              0,              0,
/*  5B  */      0,              0,              0,              0,
/*  5C  */      0,              0,              0,              0,
/*  5D  */      0,              0,              0,              0,
/*  5E  */      0,              0,              0,              0,
/*  5F  */      0,              0,              0,              0,
/*  60  */      0,              0,              0,              0,
/*  61  */      0,              0,              0,              0,
/*  62  */      0,              0,              0,              0,
/*  63  */      0,              0,              0,              0,
/*  64  */      0,              0,              0,              0,
/*  65  */      0,              0,              0,              0,
/*  66  */      0,              0,              0,              0,
/*  67  */      0,              0,              0,              0,
/*  68  */      0,              0,              0,              0,
/*  69  */      0,              0,              0,              0,
/*  6A  */      0,              0,              0,              0,
/*  6B  */      0,              0,              0,              0,
/*  6C  */      0,              0,              0,              0,
/*  6D  */      0,              0,              0,              0,
/*  6E  */      0,              0,              0,              0,
/*  6F  */      0,              0,              0,              0,
/*  70  */      0,              0,              0,              0,
/*  71  */      0,              0,              0,              0,
/*  72  */      0,              0,              0,              0,
/*  73  */      0,              0,              0,              0,
/*  74  */      0,              0,              0,              0,
/*  75  */      0,              0,              0,              0,
/*  76  */      0,              0,              0,              0,
/*  77  */      0,              0,              0,              0,
/*  78  */      0,              0,              0,              0,
/*  79  */      0,              0,              0,              0,
/*  7A  */      0,              0,              0,              0,
/*  7B  */      0,              0,              0,              0,
/*  7C  */      0,              0,              0,              0,
/*  7D  */      0,              0,              0,              0,
/*  7E  */      0,              0,              0,              0,
/*  7F  */      0,              0,              0,              0
};

scancode_t esc_key_map[] = {

};
